# fly.toml app configuration file generated for wholesale-leads-server on 2025-09-30T07:22:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wholesale-leads-server'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[mounts]
source = "db"
destination = "/app/data" 