"""
Database schema definition for the leads database.
"""

# Lead table schema
LEAD_COLUMNS = {
    "id": {"type": "INTEGER", "primary_key": True, "auto_increment": True},
    "property_address": {"type": "TEXT"},
    "city": {"type": "TEXT", "indexed": True},
    "state": {"type": "TEXT"},
    "zip": {"type": "TEXT", "indexed": True},
    "phone_numbers": {"type": "TEXT"},
    "owner_first_name": {"type": "TEXT"},
    "owner_last_name": {"type": "TEXT"},
    "list_count": {"type": "INTEGER"},
    "tag_count": {"type": "INTEGER"},
    "mailing_address": {"type": "TEXT"},
    "mailing_city": {"type": "TEXT"},
    "mailing_state": {"type": "TEXT"},
    "mailing_zip_code": {"type": "TEXT"},
    "emails": {"type": "TEXT"},
    "pics": {"type": "TEXT"},
    "apn": {"type": "TEXT"},
    "est_value": {"type": "TEXT"},
    "county": {"type": "TEXT"},
    "date_added": {"type": "TEXT"},
    "date_updated": {"type": "TEXT"},
    "last_sale_date": {"type": "TEXT"},
    "last_sale_amount": {"type": "TEXT"},
    "mailing_county": {"type": "TEXT"},
    "salesforce_lead_id": {"type": "TEXT"},
    "vacancy": {"type": "TEXT"},
    "mailing_vacancy": {"type": "TEXT"},
    "opt_out": {"type": "TEXT"},
    "property_type": {"type": "TEXT"},
    "owner_occupied": {"type": "TEXT"},
    "bedrooms": {"type": "INTEGER"},
    "bathrooms": {"type": "INTEGER"},
    "property_sqft": {"type": "TEXT"},
    "lot_size": {"type": "TEXT"},
    "year_build": {"type": "INTEGER"},
    "assessed_value": {"type": "TEXT"},
    "total_loan_balance": {"type": "TEXT"},
    "est_equity": {"type": "TEXT"},
    "est_ltv": {"type": "TEXT"},
    "mls_status": {"type": "TEXT"},
    "data_provider_ranking": {"type": "TEXT"},
    "probate": {"type": "TEXT"},
    "liens": {"type": "TEXT"},
    "pre_foreclosure": {"type": "TEXT"},
    "taxes": {"type": "TEXT"},
    "vacant": {"type": "TEXT"},
    "zoning": {"type": "TEXT"},
    "loan_type": {"type": "TEXT"},
    "loan_interest_rate": {"type": "TEXT"},
    "owner_2_first_name": {"type": "TEXT"},
    "owner_2_last_name": {"type": "TEXT"},
    "self_managed": {"type": "TEXT"},
    "pushed_to_batchdialer": {"type": "TEXT"},
    "lead_score": {"type": "INTEGER"},
    "arv": {"type": "TEXT"},
    "spread": {"type": "TEXT"},
    "pct_arv": {"type": "TEXT"},
    "location": {"type": "TEXT", "indexed": True},
    "scraped_at": {"type": "DATETIME", "default": "CURRENT_TIMESTAMP", "indexed": True},
    "created_at": {"type": "DATETIME", "default": "CURRENT_TIMESTAMP", "indexed": True},
    "is_favorite": {"type": "BOOLEAN", "default": "0", "indexed": True},
}

# Indexes for optimized queries
INDEXES = [
    {"name": "idx_location", "columns": ["location"]},
    {"name": "idx_scraped_at", "columns": ["scraped_at"]},
    {"name": "idx_created_at", "columns": ["created_at"]},
    {"name": "idx_city", "columns": ["city"]},
    {"name": "idx_zip", "columns": ["zip"]},
    {"name": "idx_property_address", "columns": ["property_address"]},
    {"name": "idx_is_favorite", "columns": ["is_favorite"]},
]

# Column mapping for CSV headers to database columns
CSV_COLUMNS = [
    "property_address",
    "city",
    "state",
    "zip",
    "phone_numbers",
    "owner_first_name",
    "owner_last_name",
    "list_count",
    "tag_count",
    "mailing_address",
    "mailing_city",
    "mailing_state",
    "mailing_zip_code",
    "emails",
    "pics",
    "apn",
    "est_value",
    "county",
    "date_added",
    "date_updated",
    "last_sale_date",
    "last_sale_amount",
    "mailing_county",
    "salesforce_lead_id",
    "vacancy",
    "mailing_vacancy",
    "opt_out",
    "property_type",
    "owner_occupied",
    "bedrooms",
    "bathrooms",
    "property_sqft",
    "lot_size",
    "year_build",
    "assessed_value",
    "total_loan_balance",
    "est_equity",
    "est_ltv",
    "mls_status",
    "data_provider_ranking",
    "probate",
    "liens",
    "pre_foreclosure",
    "taxes",
    "vacant",
    "zoning",
    "loan_type",
    "loan_interest_rate",
    "owner_2_first_name",
    "owner_2_last_name",
    "self_managed",
    "pushed_to_batchdialer",
    "lead_score",
    "arv",
    "spread",
    "pct_arv",
]

# Numeric columns that should be converted to integers
NUMERIC_COLUMNS = [
    "list_count",
    "tag_count",
    "bedrooms",
    "bathrooms",
    "year_build",
    "lead_score",
]

# SQL CREATE TABLE statement
CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS leads (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    property_address TEXT,
    city TEXT,
    state TEXT,
    zip TEXT,
    phone_numbers TEXT,
    owner_first_name TEXT,
    owner_last_name TEXT,
    list_count INTEGER,
    tag_count INTEGER,
    mailing_address TEXT,
    mailing_city TEXT,
    mailing_state TEXT,
    mailing_zip_code TEXT,
    emails TEXT,
    pics TEXT,
    apn TEXT,
    est_value TEXT,
    county TEXT,
    date_added TEXT,
    date_updated TEXT,
    last_sale_date TEXT,
    last_sale_amount TEXT,
    mailing_county TEXT,
    salesforce_lead_id TEXT,
    vacancy TEXT,
    mailing_vacancy TEXT,
    opt_out TEXT,
    property_type TEXT,
    owner_occupied TEXT,
    bedrooms INTEGER,
    bathrooms INTEGER,
    property_sqft TEXT,
    lot_size TEXT,
    year_build INTEGER,
    assessed_value TEXT,
    total_loan_balance TEXT,
    est_equity TEXT,
    est_ltv TEXT,
    mls_status TEXT,
    data_provider_ranking TEXT,
    probate TEXT,
    liens TEXT,
    pre_foreclosure TEXT,
    taxes TEXT,
    vacant TEXT,
    zoning TEXT,
    loan_type TEXT,
    loan_interest_rate TEXT,
    owner_2_first_name TEXT,
    owner_2_last_name TEXT,
    self_managed TEXT,
    pushed_to_batchdialer TEXT,
    lead_score INTEGER,
    arv TEXT,
    spread TEXT,
    pct_arv TEXT,
    location TEXT,
    scraped_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
"""
